# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

ModuleNotFoundError: No module named 'mdutils'

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np
np.random.seed(123)

#### 2. Print the numpy version and the configuration (★☆☆)
blas_mlk is the blas for intel library

In [3]:
print(np.__version__)
print(np.show_config())

1.20.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


#### 3. Create a null vector of size 10 (★☆☆)
There are three fundamental objects used to describe the data in an array: 1) the ndarray itself, 2) the data-type object that describes the layout of a single fixed-size element of the array, 3) the array-scalar Python object that is returned when a single element of the array is accessed. See [here](https://numpy.org/doc/stable/reference/arrays.html#id1)

In [4]:
my_empty = np.empty((10, ))
my_empty

array([4.67603223e-310, 0.00000000e+000, 2.46151512e-312, 2.33419537e-312,
       2.31297541e-312, 2.56761491e-312, 2.05833592e-312, 6.79038654e-313,
       2.37663529e-312, 6.92141349e+218])

#### 4. How to find the memory size of any array (★☆☆)
An instance of class ndarray consists of a contiguous one-dimensional segment of computer memory (owned by the array, or by some other object), combined with an indexing scheme that maps N integers into the location of an item in the block. The ranges in which the indices can vary is specified by the shape of the array. How many bytes each item takes and how the bytes are interpreted is defined by the data-type object associated with the array. See [here](https://numpy.org/doc/stable/reference/arrays.ndarray.html#id1) for more.

In [5]:
my_empty.nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
?np.add

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
b = np.empty((10, ))
b.itemset(4, 1) # b[4] = 1
b

array([4.67603223e-310, 0.00000000e+000, 2.46151512e-312, 2.33419537e-312,
       1.00000000e+000, 2.56761491e-312, 2.05833592e-312, 6.79038654e-313,
       2.37663529e-312, 6.92141349e+218])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
np.array(range(10, 50))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
np.array(range(10, 50))[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
np.array(range(0, 9)).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
a = np.array([1,2,0,0,4,0])
np.where(a != 0)  # np.nonzero(a)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
np.random.random_sample(size=(3,3,3))

array([[[0.69646919, 0.28613933, 0.22685145],
        [0.55131477, 0.71946897, 0.42310646],
        [0.9807642 , 0.68482974, 0.4809319 ]],

       [[0.39211752, 0.34317802, 0.72904971],
        [0.43857224, 0.0596779 , 0.39804426],
        [0.73799541, 0.18249173, 0.17545176]],

       [[0.53155137, 0.53182759, 0.63440096],
        [0.84943179, 0.72445532, 0.61102351],
        [0.72244338, 0.32295891, 0.36178866]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
np.random.random_sample(size=(10,10)).min()

0.002688064574320692

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
np.random.random_sample(size=(30, )).mean()

0.5078714702038956

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
a = np.ones((4,4))
a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
a = np.ones((4,4))
np.pad(a, (1, 1), 'constant', constant_values=(0))
# a = [1, 2, 3, 4, 5]
# np.pad(a, (2, 10), 'constant', constant_values=(4, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
print(0 * np.nan) # nan infects like viruses
print(np.nan == np.nan) # nans are different else nan / nan would give 1
print(np.inf > np.nan)  # comparaison between nan and other returns False
print(np.nan - np.nan)  # nan
print(np.nan in set([np.nan])) # True because identity has higher priority than equality, same two objects
print(0.3 == 3 * 0.1) # floating point problem

nan
False
False
nan
True
False


In [19]:
# python identity id
# python equality =
# python memory address is

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [20]:
np.diag(np.arange(1, 5, 1), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [21]:
a = np.ones((8,8), dtype=int)
a[1::2, ::2] = 0
a[::2, 1::2] = 0
print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [22]:
a = np.arange(0, 6*7*8, 1).reshape((6,7,8))
np.unravel_index(100, a.shape) 
# takes an index and a shape, and creates real coordinates that match the index
# given as argument in a flat (unraveled) array

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [23]:
a = np.tile([[1, 0], [0,1]], (4,4))
print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [24]:
a = np.random.rand(5,5)
(a - a.mean()) / a.std()

array([[ 1.26228082,  0.59456012, -0.29778862, -0.30515618,  0.83434151],
       [ 0.13905183, -1.53678269,  0.19841461,  1.00775986, -0.65775441],
       [ 1.40074254,  0.78421651,  0.16841   ,  0.78744796, -1.55684512],
       [ 1.1630434 ,  1.0309778 ,  1.33902384, -1.38435185, -1.54767311],
       [-1.35024387, -0.44053592, -0.3536373 ,  0.12711721, -1.40661896]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [25]:
color = np.dtype(
    [
        ("r", np.ubyte, 1), ("g", np.ubyte, 1),
        ("b", np.ubyte, 1), ("a", np.ubyte, 1)
    ]
)
color
a = np.asarray("r g b".split(" "))  # ??
a

<ipython-input-25-5163293e632b>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype(


array(['r', 'g', 'b'], dtype='<U1')

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [26]:
A = np.reshape(range(1, 16), (5,3))
B = np.tile([0, 1], (3,1))
print("{} * {}".format(A, B))
print("result:\n", A.dot(B))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]] * [[0 1]
 [0 1]
 [0 1]]
result:
 [[ 0  6]
 [ 0 15]
 [ 0 24]
 [ 0 33]
 [ 0 42]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [27]:
a = np.arange(1, 10)
a[(a >= 3) & (a <= 8)] *= -1
a

array([ 1,  2, -3, -4, -5, -6, -7, -8,  9])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [28]:
Z = np.arange(1, 10)
#Z**Z
# 2 << Z >> 2 ??
#Z <- Z ??
#1j*Z
#Z/1/1

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [29]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-29-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-29-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [30]:
# round using sup for a>0 else inf for a<=0
a = np.random.uniform(-10,+10,10)
print(a)
print(np.where(a>0, np.ceil(a), np.floor(a)))
print(np.copysign(np.ceil(np.abs(a)), a))
# print(np.ceil(a)) wrong because it does not depend on the sign

[-5.97200997  6.23288697 -0.64024852  6.15876419 -9.85147243  1.03185452
  8.63864296  1.64350918 -5.87808545  4.35515125]
[ -6.   7.  -1.   7. -10.   2.   9.   2.  -6.   5.]
[ -6.   7.  -1.   7. -10.   2.   9.   2.  -6.   5.]


#### 30. How to find common values between two arrays? (★☆☆)

In [31]:
a = np.asarray([range(1, 21), range(1, 21)])
b = np.arange(15, 22)
print(b[np.isin(b, a)])
print(b[np.isin(b, a, invert=True)])
print(a[np.isin(a, b)])  # broadcasting over a
# for 1D there is also intersect1d

[15 16 17 18 19 20]
[21]
[15 16 17 18 19 20 15 16 17 18 19 20]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [32]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [33]:
np.emath.sqrt(-1)  # convert to complex domain

1j

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [34]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [35]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)


In [36]:
def myf(a):
    return a

In [37]:
a = np.ones((2,2), dtype=float)
b = 3*np.ones((2, 2), dtype=float)

myf(np.add(a, b, out=a))

array([[4., 4.],
       [4., 4.]])

In [38]:
# https://numpy.org/doc/stable/reference/ufuncs.html#math-operations
a = np.ones(2, dtype=float)
b = 3*np.ones((2, 2), dtype=float)
np.add(a, b, out=b)
np.divide(a, 2, out=a)
np.negative(a, out=a)
np.multiply(a, b, out=b)

array([[-2., -2.],
       [-2., -2.]])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [39]:
a = np.random.uniform(0, 9, 10)
print(a.round())
print(np.floor(a))
print(np.ceil(a))
print(np.rint(a))
print(np.trunc(a))
print(a.astype(int))

[3. 6. 0. 6. 0. 7. 4. 1. 5. 1.]
[3. 6. 0. 5. 0. 6. 4. 1. 4. 0.]
[4. 7. 1. 6. 1. 7. 5. 2. 5. 1.]
[3. 6. 0. 6. 0. 7. 4. 1. 5. 1.]
[3. 6. 0. 5. 0. 6. 4. 1. 4. 0.]
[3 6 0 5 0 6 4 1 4 0]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [40]:
print(np.tile(range(0, 5), (5,1)))

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [41]:
np.asarray(range(0, 11), dtype=np.int16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int16)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [42]:
np.linspace(0, 11, 1, endpoint=False)[1:]

array([], dtype=float64)

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [43]:
a = np.random.randint(0, 10, 10)
a.sort()
print(a)

[0 1 3 3 3 5 6 7 7 7]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [44]:
Z = np.arange(4)
np.add.reduce(Z)

6

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [45]:
# note that floating precision errors are not considered != rust
myt = np.float64
a = np.arange(1.10, 3.1, dtype=myt)
b = np.arange(1.12, 3.1, dtype=myt)
c = np.arange(0, 2, dtype=myt)
d = np.arange(1, 4, dtype=myt)

# Assuming identical shape of the arrays (error otherwise) and a tolerance for the comparison of values
equal = np.allclose(a,b, rtol=0.1)
print(equal)
equal = np.allclose(a,b, rtol=0.01)
print(equal)
equal = np.allclose(a,c)
print(equal)
#equal = np.allclose(a,d) # error
#print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
print("\narray_equal")
equal = np.array_equal(a, b)
print(equal)
equal = np.array_equal(a, c)
print(equal)
equal = np.array_equal(a, d)
print(equal)

True
False
False

array_equal
False
False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [46]:
a = np.arange(1, 10, dtype=np.int16)
a.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [47]:
a = np.random.randint(-10, 10, 10)
print(a.max())
a[a.argmax()] = 0
print(a.max())

9
7


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [48]:
a = 3*np.ones(2, dtype=np.int16)
a[1::2] -= 1
print(a)
b = np.ones(2, dtype=np.int16)
b[1::2] -= 1
print(b)
print("\n", 1 / np.subtract.outer(a, b))

[3 2]
[1 0]

 [[0.5        0.33333333]
 [1.         0.5       ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)